### ISSUE TITLE
PEPC subject line says eBrochure request

### ISSUE THREAD

**Issue by chrisbutzke** [stelter/StelterIGXBackend#34]
/Action/PEPCSendEmail.cshtml
Lines 55-57 should be something like this:
String.Format(orgName + ": PEPC request from " + fname + " " + lname)
:
String.Format("PEPC request from " + fname + " " + lname)

This commit history shows what the subject line code used to be:
https://github.com/stelter/StelterIGXBackend/commit/04c09baf132f5657e921306082e4da7fe6adde6f#diff-d864b3ace254ec25d19b8237503084cd

**Comment by PaulSearcy** [comment]
Updated it to look like this. String.Format is loosely like string literals ` ` in JS

```c#
mail.Subject = orgName != null && orgName.Length > 0 ?
    String.Format("{0}: PEPC request from {1} {2}", orgName, fname, lname)
:
    String.Format("PEPC request from {0} {1}", fname, lname);
```
